stripe/stripe-js

tests/types/index.ts
types/stripe-js/elements.d.ts
types/stripe-js/elements/payment-request-button.d.ts

Fixes #3 
Will follow with a fix for stripe.com/docs/js, which doesn't document this well.

Fix Payment Request Button element creation types

---

tests/types/index.ts
types/stripe-js/elements/card-number.d.ts

Adds `showIcon` and `iconStyle` types to `StripeCardNumberElementOptions`.

Add types for showIcon option

---

types/stripe-js/checkout.d.ts
types/stripe-js/elements.d.ts
types/stripe-js/index.d.ts

Adds `pt-BR` as a supported locale, plus a few others that I noticed were missing from the types.

Update supported locale types

---

README.md

Removing the contributing section as it links to CONTRIBUTING.md which does not exist
tests pass, 🚢

Removing contributing section with broken link

---

types/stripe-js/elements.d.ts
types/stripe-js/index.d.ts

Adds recently unbeta'd Elements locales to the relevant types.

Add new Elements locales types

---

types/stripe-js/checkout.d.ts
types/stripe-js/elements.d.ts
types/stripe-js/index.d.ts

Add es-419 (Spanish - Latin America) locale to Elements and Checkout.
cc @christopher-stripe 
Will update the docs in a follow-up PR.

Add es-419 locale

---

tests/types/index.ts
types/stripe-js/index.d.ts
types/stripe-js/payment-intents.d.ts

Add wrapper of `ConfirmAlipayPayment` and public release Alipay PI/PM
I wrote unit tests.
Gated doc here: https://stripe.com/docs/js/payment_intents/confirm_alipay_payment
Will ungate the doc right after public release.

add ConfirmAlipayPayment

---

tests/types/index.ts
types/api/PaymentMethods.d.ts
types/stripe-js/index.d.ts
types/stripe-js/payment-intents.d.ts

Add typing support for GrabPay flows.
Added automated tests for the new types.

Add GrabPay support

---

tests/types/index.ts
types/stripe-js/payment-intents.d.ts

Fix for #218, added `network` to `ConfirmCardPaymentData`
Added entry to tests/types/index.ts to verify:

Add `network` to `ConfirmCardPaymentData`

---

.github/workflows/test.yml
.travis.yml

Migrates from Travis CI to GitHub actions. 
The workflow can successfully be seen running in this PR. I also tested intentionally creating an error, which failed the check.

Migrate to GitHub Actions

---

tests/types/index.ts
types/stripe-js/elements.d.ts
types/stripe-js/elements/link-authentication.d.ts

Added LinkAuthentication types 
Added tests to `tests/types/index.ts`

Add LinkAuthentication types

---

tests/types/index.ts
types/stripe-js/elements.d.ts
types/stripe-js/elements/shipping-address.d.ts

Added shipping address types for shipping address element. 
Added tests to tests/types/index.ts

Add shipping address types

---

types/stripe-js/elements.d.ts
types/stripe-js/elements/shipping-address.d.ts

Update name from StripeShippingAddressOptions to StripeShippingAddressElementOptions
Tests continue to pass.

Update name for shipping address element options

---

tests/types/src/valid.ts
types/stripe-js/elements-group.d.ts
types/stripe-js/elements/link-authentication.d.ts

- Add types for LAE `defaultValues` option

Add types for LAE defaultValues

---

tests/types/src/valid.ts
types/stripe-js/elements/link-authentication.d.ts

Add value.email to LAE change event payload

---

tests/types/src/valid.ts
types/stripe-js/payment-intents.d.ts
types/stripe-js/setup-intents.d.ts
types/stripe-js/stripe.d.ts

Update collectBankAccount typing. 
Added automated tests for the new types.

Update collectBankAccount typing 

---

tests/types/src/valid.ts
types/stripe-js/elements-group.d.ts

Adds a type for `elements.fetchUpdates()`
Added a unit test.

Add fetchUpdates type

---

tests/types/scripts/test.mjs

This PR fixes a typo.
`incompability` -> `incompatibility`
I ran the following commands.
```
$ yarn lint
$ yarn prettier
```

fix typo incompability -> incompatibility

---

tests/types/src/valid.ts
types/stripe-js/elements/address.d.ts

Adds types for display option for AE. 
Updated test.

Add display option for AE

---

tests/types/src/invalid.ts
tests/types/src/valid.ts
types/stripe-js/elements-group.d.ts
types/stripe-js/elements/address.d.ts
types/stripe-js/elements/cart.d.ts
types/stripe-js/elements/index.d.ts
types/stripe-js/elements/link-authentication.d.ts
types/stripe-js/elements/shipping-address.d.ts

Adds cart types, including the lineitemclick and checkout events which are unique to cart.
Also adds types that were forgotten for LAE, AE, and SAE.
Wrote unit tests for valid and invalid cases.
Yes, the documentation was already up and flipped to public today.

Added cart types + missing LAE, AE, SAE types

---

tests/types/src/invalid.ts
tests/types/src/valid.ts
types/stripe-js/elements/cart.d.ts

- Added `show`, `hide`, `cancelCheckout` and `addLineItem` properties 
- Added missing `| null` to optional properties like `header.text`
- Removed `clientSecret` from updatable properties
- Added tests in `valid.ts` and `invalid.ts`

Add cart actions

---

types/stripe-js/elements/payment-method-messaging.d.ts

Add typings for the PaymentMethodMessaging Element

Update types for PMM element

---

tests/types/src/invalid.ts
tests/types/src/valid.ts
types/stripe-js/elements-group.d.ts
types/stripe-js/elements/index.d.ts
types/stripe-js/elements/pay-button.d.ts
types/stripe-js/elements/payment.d.ts

Adds types for the `payButton` element.
Wrote unit tests for valid and invalid cases.
Since the element is currently in beta, the updated documentation is not public.

Add types for payButton element

---

types/stripe-js/elements-group.d.ts

Fixes typo on `payButton` Element types added in #381.

Fixes typo on payButton Element types

---

types/stripe-js/elements-group.d.ts

Remove beta access comments for Address Element.
Updating comments only.

AE: Remove beta comments

---

tests/types/src/valid.ts
types/stripe-js/payment-request.d.ts

Fix type issue raised in https://github.com/stripe/stripe-js/issues/390. Adding `link` as one of the `PaymentRequestWallet`.
Updated tests.

Add Link PRB types

---

types/stripe-js/elements-group.d.ts
types/stripe-js/elements/payment.d.ts

Adds TS types for the new layout features on the Payment Element
Updated TS defintions.

Adds TS types for the new PE layout feature

---

tests/types/src/valid.ts
types/stripe-js/elements/address.d.ts

This PR adds types for the `getValue` method for the Address Element. 
Added type validation tests in valid.js.

Add AE getValue type

---

tests/types/src/valid.ts
types/stripe-js/payment-intents.d.ts
types/stripe-js/setup-intents.d.ts
types/stripe-js/stripe.d.ts

Type support for for Cash App GA. 
Automated tests in tests/types/src/valid.ts.

Type support for for Cash App

---

tests/types/src/valid.ts
types/stripe-js/elements/payment-request-button.d.ts

We are adding a feature to potentially show multiple buttons within the Payment Request Button, and these new fields should be added to the Typescript definitions for this library.
Yes, the documentation change is in-flight.

Update Typescript definitions for new Payment Request Button options

---

tests/types/src/valid.ts
types/stripe-js/elements-group.d.ts

This PR adds the `paymentMethodCreation` parameter and updates the case of some of the other new parameters
I updated the tests in `valid.ts`

Update elements options for deferred intent

---

types/stripe-js/elements/payment-method-messaging.d.ts

Type addition to PMME

---

tests/types/src/valid.ts
types/stripe-js/elements/express-checkout.d.ts

Updates to the most recent API 
Added valid types test

Update ExpressCheckout layout types

---

README.md

Adds a note on versioning of this library vs Stripe.js to README preamble.
Tests N/A, this is a docs change only.

[docs] Add versioning note to README

---

types/stripe-js/elements-group.d.ts

ECE is no longer in beta, so removing mentions of that in the comments.
Docs edits

Remove mentions of ECE being in beta

---

types/stripe-js/custom-checkout.d.ts

Update Types of CustomCheckout async actions

Update Types of CustomCheckout async actions

---

tests/types/src/valid.ts
types/stripe-js/elements-group.d.ts

Update type definition for UPE now that we will allow passing a `payment_method_configuration` parameter.
Added validation invocation to test type addition.

Update types for Payment Method Configuration usage

---

types/stripe-js/custom-checkout.d.ts

Allow pass null to updateShipping|BillingAddress

Allow pass null to updateShipping|BillingAddress

---

README.md

Update ReadME to inform users on v3.0.0 issues

Update ReadME to inform users on v3.0.0 issues

---

README.md

Update README with new notice to inform users on new fix for v3.0.x package issues

Update README with 3.0.x notice

---

types/stripe-js/setup-intents.d.ts

This is a fix for #559 
Tested manually with `yarn link`

Fix ConfirmCashappSetupOptions typing

---

.gitignore
lib/index.d.mts
lib/index.d.ts
lib/index.js
lib/index.mjs
package.json
pure/index.d.mts
pure/index.d.ts
pure/index.js
pure/index.mjs
rollup.config.js
scripts/copy-types
yarn.lock

This is a redo of #565, with a fixed import path for the main module.
This was tested against the example Stripe.js installations.

Improved type mismatch fix

---

types/stripe-js/elements/apple-pay.d.ts

Update ApplePay option type

---

types/stripe-js/custom-checkout.d.ts

Update Custom Checkout SDK type

Update Custom Checkout SDK type

---

types/api/payment-methods.d.ts
types/stripe-js/elements-group.d.ts

We allow users to update `customerSessionClientSecret`, updating types to reflect that.

Update StripeElementsUpdateOptions with customerSessionClientSecret

---

types/stripe-js/embedded-checkout.d.ts

Add onLineItemsChange option for embeddedCheckout

Add onLineItemsChange option for embeddedCheckout

---

tests/types/src/valid.ts
types/stripe-js/payment-intents.d.ts
types/stripe-js/stripe.d.ts

Adds type support for Multibanco and TWINT, since both are now GA
Automated tests in tests/types/src/valid.ts.

Add Type Support for Multibanco and Twint

---

types/stripe-js/custom-checkout.d.ts

Update Custom Checkout SDK type

Update Custom Checkout SDK types

---

types/stripe-js/checkout.d.ts

Update CheckoutSdk confirm args type

Update CheckoutSdk confirm args type

---

types/stripe-js/checkout.d.ts

Fix updateShippingOption response type

Fix updateShippingOption response type

---

tests/types/src/valid.ts
types/api/payment-intents.d.ts

Fixes https://github.com/stripe/stripe-js/issues/683
Added test

Add missing types to Payment Intent Next Actions

---

types/stripe-js/checkout.d.ts

Add runServerUpdate interface to checkout sdk

Add runServerUpdate interface to checkout sdk

---

types/stripe-js/checkout.d.ts

Fix runServerUpdate type

---

tests/types/src/valid.ts
types/stripe-js/elements/express-checkout.d.ts

- Updating TS types for ECE New Integration Shape
- Added valid lint tests
- Didn't add invalid lint tests as we are marking fields as deprecated, which doesn't throw lint errors

Update types for ECE new integration shape

---

types/stripe-js/checkout.d.ts

Add types for checkout.updateTaxIdInfo and session.taxIdInfo

---

package.json

This flips off the release candidate for now, completing testing.
I will run a final release with `./scripts/publish patch` to ensure that regular release changelogs work correctly when there are intermediate release candidate changes.

Complete release candidate testing

---

README.md

Revert the readme until the release.

revert readme until release

---

tests/types/src/valid.ts
types/stripe-js/stripe.d.ts

Adds types for new Stripe constructor developer tools options.
Added test cases.

Add developer tools typings

---

tests/types/src/valid.ts
types/stripe-js/checkout.d.ts

Updates the Elements with Checkout Session types to be the GA shape.
Added a valid test.

Modify Elements with Checkout Session types for GA

---

README.md
package.json

Update the readme for Basil and set release candidate flag to false.

Update readme for Basil

---

tests/types/src/valid.ts
types/stripe-js/elements/payment-method-messaging.d.ts

- Mark country as optional
- Update list of currency and countryCode values
TS type test omits `countryCode`

Update PMME currency and countryCode types

---

tests/types/src/valid.ts
types/stripe-js/elements-group.d.ts

Adds `currency` parameter to `elements` group with clientSecret.
Added tests to `valid.ts`

Add currency to elements group with clientSecret

---

tests/types/src/valid.ts
types/stripe-js/elements/payment.d.ts

Add Billing Details Type for Payment Element Change Event

Add Types for Billing Details in Payment Element Change Event

---

tests/types/src/invalid.ts
tests/types/src/valid.ts
types/stripe-js/checkout.d.ts
types/stripe-js/elements/index.d.ts
types/stripe-js/elements/tax-id.d.ts

- Adding types for Tax ID Element
- Added lint unit tests

Add public types for Tax Id Element

---

scripts/publish

Removes the doubly check for the github token.  We already check for it in the `verify_prerequisites` function

Removes double github token check

---

types/stripe-js/elements-group.d.ts

Support the new Elements Appearance API variable

Add buttonBorderRadius to types
